name: Trigger auto deployment for innovati-technical-test-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/innovati-technical-test-app-AutoDeployTrigger-3b8c956d-33a9-4a60-b30f-c40440d019b6.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.INNOVATITECHNICALTESTAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.INNOVATITECHNICALTESTAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.INNOVATITECHNICALTESTAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: innovatitechnical.azurecr.io
          registryUsername: ${{ secrets.INNOVATITECHNICALTESTAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.INNOVATITECHNICALTESTAPP_REGISTRY_PASSWORD }}
          containerAppName: innovati-technical-test-app
          resourceGroup: innovati
          imageToBuild: innovatitechnical.azurecr.io/innovati-technical-test-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


